config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#dashboard"
  get "up" => "rails/health#show", as: :rails_health_check

  get "/dashboard", to: "pages#dashboard", as: "dashboard"
  get "/tenanthistory", to: "pages#tenanthistory", as: "tenanthistory"
  get "houses/:house_id/ownerhistory", to: "pages#ownerhistory", as: "ownerhistory"

  resources :houses do
    resources :rooms, only: [:new, :create, :edit]
  end

  resources :rooms, except: [:create, :edit] do
    resources :tickets, only: [:new, :create]
  end

  resources :tickets do
      resources :messages, only: :create
  end

end

app/controllers/houses_controller.rb
class HousesController < ApplicationController
  before_action :set_house, only: [:show]

  def index
    @houses = current_user.houses
    # if params[:query].present?
    #   sql_subquery = "name ILIKE :query OR address ILIKE :query"
    #   @house = @houses.where(sql_subquery, query: "%#{params[:query]}%")
    # end
  end

  def show
    @room = Room.new
    @house = House.find(params[:id])

  end

  def new
    @house = House.new
  end

  def create
    @house = House.new(house_params)

    # connect
    @house.user = current_user
    @room = Room.new

    if @house.save
      redirect_to house_path(@house)
      # respond_to do |format|
      #   format.html { redirect_to house_path(@house) }
      #   format.json
      # end

    else
      render :new, status: :unprocessable_entity
      # respond_to do |format|
      #   format.html { render :new, status: :unprocessable_entity }
      #   format.json
      # end
    end
  end

  def edit
    puts "helloooooo edit"
    @house = House.find(params[:id])
  end

  def update
    puts "helloooooooo update"
    @house = House.find(params[:id])
    @house.update(house_params)
    @room = Room.new
    redirect_to house_path(@house)

    # respond_to do |format|
    #   format.html { redirect_to house_path(@house) }
    #   format.text { render partial: "houses/houseDetails", locals: { house: @house, room: @room }, formats: [:html] }
    # end
  end

  def destroy
    @house = House.find(params[:id])
    @house.destroy
    redirect_to dashboard_path, status: :see_other
  end

  private

  def set_house
    @house = House.where(user_id: current_user)
  end

  def house_params
    params.require(:house).permit(:address, :name, :capacity, :photo)
  end

end

app/views/houses/_formHouse.html.erb
<div class="container" data-controller="create-house" style="background: #60D3AB; height:100vh;" >

  <div class="title" style="margin-bottom: 40px">Your New House</div>
  <div style="padding: 28px">
    <%= simple_form_for @house do |f|%>
      <%= f.input :name ,
          input_html: { class: "form-input" },
          placeholder: "House nickname *",
          label:false%>
      <%= f.input :address,
          input_html: { class: "form-input-address"},
          placeholder: "House address *",
          label: false %>
      <%= f.input :capacity,
          input_html: { class: "form-input" },
          placeholder: "Tenant capacity",
          label: false %>
      <%= f.input :photo, as: :file,
          input_html: { class: "form-input" },
          placeholder: "pic",
          label: false %>
      <div style="text-align: center; padding-top: 30px">
      <%= f.submit "Save house", class: "btn btn-flat w-75" %>
      </div>
    <% end %>
    </div>
</div>

app/views/houses/_formRoom.html.erb
<div class="px-5">
  <%= simple_form_for [house, room] do |f| %>
    <div class="row py-3">

      <div class="col-6 formTags">
        <%= f.input :number %>
      </div>

      <div class="col-6 formTags">
        <%= f.input :user, collection: User.all, label_method: :email, value_method: :id%>
      </div>
    </div>

    <div class="row">
      <div class="col-4 formTags">

        <%= f.submit "Add room", class: "btn btn-flat mb-3",
        data: {
          create_room_target: "button"
        }%>
      </div>
    </div>
  <% end %>
</div>

app/views/houses/_houseCard.html.erb
<%# product card UI KIT %>
<div class="card-house">
  <% if house.photo.attached? %>
    <%= cl_image_tag house.photo.key, height: 300, width: 400, crop: :fill %>
  <% end %>

  <div class="card-house-infos">
    <h2><%= house.name %></h2>
    <p><%= house.address %></p>
    <% house_tickets = 0 %>
    <% house.rooms.each do |room| %>
      <% house_tickets += room.tickets.where(status: "Pending").count %>
    <% end %>
      <% if  house_tickets != 0  %>
        <div class="notification-bubble text-center" style="color:#fff"><%= house_tickets %></div>
      <% end  %>
  </div>

</div>

app/views/houses/_houseDetails.html.erb
<div class="", style="background:#60D3AB" data-controller="create-room">
  <div class="">
    <h1 class="title p-3"><%= @house.name %></h1>
    <h4 class="smalltext address px-3"><%= @house.address %></h4>


    <%# picture %>
    <% if @house.photo.attached? %>
      <div class="show-house-image text-center mb-3">
        <%= cl_image_tag @house.photo.key, :crop=>"fill"%>
      </div>
    <% end %>

  </div>

  <%# JS target  and rooms form%>
  <div data-create-room-target="list" class="px-3" style="padding-bottom: 95px">
    <h4 class="mediumtext address alignRight pb-2">Rented rooms: <span id="rooms-number"><%= @house.rooms.count %> / <%= @house.capacity %></span></h4>

    <%# <%= link_to "Rent a room", new_house_room_path(house), data: { action: "click->create-room#displayForm" } %>

    <%# <%= link_to new_house_room_path(house), class:"d-flex my-3", data: { action: "click->create-room#displayForm" } do %>
        <%# <div class="plus-room"> %>
        <%# <i class="fa fa-plus plus-room-icon"></i> %>
        <%# </div> %>
        <%# <h4 class="rooms-rented mylink px-3">Rent a room</h4> %>
    <%# <% end %>


    <% if @house.rooms.count < @house.capacity%>
      <details class="ourDetailsTag my-3">
        <summary class="rooms-rented alignCenter ourDetailsTag-sum mx-5">Rent a room</summary>
        <%= render "houses/formRoom", house: house, room:room %>
      </details>
    <% end %>








    <div data-create-room-target="formContainer" class="d-none">
      <div class="w-100 p-3"><%= render "formRoom", house: house, room: room %></div>
    </div>


     <% all_tickets = 0 %>
    <% house.rooms.each do |room| %>
      <% all_tickets += room.tickets.where(status: "Pending").count %>
    <% end %>
      <% if  all_tickets != 0  %>
        <h5 class="list_title pt-2">Tickets</h5>
    <% else %>
    <h5 class="list_title pt-2">No Tickets</h5>
    <% end %>

    <%# check there are rooms - a não ser que não haja rooms corre isto %>
    <% unless @room.nil?  %>

      <% house.rooms.each do |room| %>
        <div class="list-group list-group-flush">

          <%# display tickets of each room %>
          <% room.tickets.each do |ticket| %>
            <% if ticket.status != "Fixed" %>
              <%= link_to ticket_path(ticket), class:"list-group-item list-group-item-action flex-column align-items-start bg-our-back-green", style:"border-top: 1px solid white;" do %>
                <div class="d-flex w-100 justify-content-between">
                  <h5 class="mb-1 mt-2"><strong><%= ticket.title %></strong></h5>
                  <small class="mb-1 mt-2 status-pills status-owner-<%= ticket.status.split(" ").join.downcase %> "><%= ticket.status%></small>
                </div>
                <p class="mb-1"><%=ticket.description.truncate(40) %></p>
              <% end %>

            <% end %>
          <% end %>

        </div>
      <% end %>
    <% end %>
  </div>


<div class="btn-group dropup">
 <button type="button" class="float dropdown-toggle" id="bg-grey" data-bs-toggle="dropdown" aria-expanded="false">
    <i class="fa-solid fa-pencil my-float-edit"></i>
  </button>

  <ul class="dropdown-menu">
    <li>
      <%= link_to edit_house_path(house), class:"dropdown-item" do %>
      <p>Edit house details</p>
      <% end %>
    </li>

    <li>
      <%= link_to house_path(house), class:"dropdown-item", method: :delete, data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } do %>
      <p>Delete this house</p>
      <% end %>
    </li>

    <li>
      <%= link_to ownerhistory_path(house), class:"dropdown-item" do %>
      <p>Solved tickets</p>
      <% end %>
    </li>




  </ul>
</div>


  <%# <div class="btn-group dropup">
    <button type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <i class="fa-solid fa-pencil my-float-edit"></i>
    </button>
    <div class="dropdown-menu"> %>
      <!-- Dropdown menu links -->
        <%# <button class="dropdown-item" type="button">Action</button> %>


      <%# <%= link_to edit_house_path(house) do %>
        <%# <i class="fa-solid fa-pencil my-float-edit"></i> %>
      <%# <% end %>

    </div>
</div>





</div>

app/views/houses/_houseList.html.erb
<div class="container px-4" style="padding-bottom: 95px">
  <div class="list_title">My Houses</div>
  <% @sorted_houses.each do |house| %>

    <%= link_to house_path(house) do %>

      <%= render "houses/houseCard", house: house %>

    <% end %>

  <% end %>

  <%= link_to new_house_path, class: "float" do %>
    <i class="fa fa-plus my-float"></i>
  <% end %>

</div>

app/views/houses/edit.html.erb
<%= render partial: 'formHouse' %>
<div class="container">
  <%= link_to "Delete",
    house_path(@house),
    data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}
  %>

  <%= link_to "Back",  house_path%>
</div>

app/views/houses/new.html.erb
 <%= render partial: 'formHouse' %>

app/views/houses/show.html.erb
<div class="wrapper bg-our-back-green" style="height: 100vh">
    <%= render "houseDetails", house: @house, room: @room %>
</div>