config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#dashboard"
  get "up" => "rails/health#show", as: :rails_health_check

  get "/dashboard", to: "pages#dashboard", as: "dashboard"
  get "/tenanthistory", to: "pages#tenanthistory", as: "tenanthistory"
  get "houses/:house_id/ownerhistory", to: "pages#ownerhistory", as: "ownerhistory"

  resources :houses do
    resources :rooms, only: [:new, :create, :edit]
  end

  resources :rooms, except: [:create, :edit] do
    resources :tickets, only: [:new, :create]
  end

  resources :tickets do
      resources :messages, only: :create
  end

end

app/views/pages/dashboard.html.erb
<div class="wrapper">
  <%# the two buttons to change view %>
  <ul class="nav nav-tabs" style="border: none !important" id="myTab" role="tablist">
    <li class="nav-item user-select bg-our-back-green no-border" style="border: none !important" role="presentation">
      <a class="nav-link bg-our-back-green active no-border" style="border: none !important" id="owner-tab" data-bs-toggle="tab" href="#owner" role="tab" aria-controls="owner" aria-selected="true">Owner</a>
    </li>
    <li class="nav-item user-select bg-our-back-orange" style="border: none !important" role="presentation">
      <a class="nav-link bg-our-back-orange" style="border: none !important" id="tenant-tab" data-bs-toggle="tab" href="#tenant" role="tab" aria-controls="tenant" aria-selected="false">Tenant</a>
    </li>
  </ul>

  <%# what happens when you click on the tab%>
  <%# Tab contents %>
  <div class="tab-content no-border h-100" >
    <div class="tab-pane fade bg-our-back-green <%= if params[:tab] != "tenant" then "show active" else "" end %> " style="height: 100%; min-height: 100vh" id="owner" role="tabpanel" aria-labelledby="owner-tab">

    <% unless current_user.houses.empty? %>

    <%# --- search bar %>
      <div class="w-100 p-3">
        <%= form_with url: dashboard_path, method: :get, class: "d-flex" do %>
          <%= text_field_tag :query,
                params[:query],
                class: "form-control",
                placeholder: "Search for a house!"
            %>

          <%= submit_tag "Search", name: "", class: "btn btn-primary" %>
        <% end %>
      </div>

    <%# owner view %>
      <%= render "houses/houseList" %>
    <% else %>

      <h5 class="p-5">Add your houses !</h5>
      <%= link_to new_house_path, class: "float" do %>
        <i class="fa fa-plus my-float"></i>
      <% end %>

    <% end %>
  </div>



    <%# --- tenant view %>
    <div class="tab-pane fade bg-our-back-orange <%= if params[:tab] == "tenant" then "show active" else "" end %> " style="height: 100%; min-height: 100vh" id="tenant" role="tabpanel" aria-labelledby="tenant-tab">
      <% unless current_user.room.nil? %>

        <%# address %>
        <h5 class="p-3"><%= current_user.room.house.address %></h5>

        <%# toggle the form via button %>
        <div data-controller="toggle" class="d-flex align-items-center" id="togglecontroller">
          <button data-action="click->toggle#fire" data-toggle-target="button" class="btn add-ticket_btn m-5">
            <div class="add-ticket-plus_btn">
              <i class="fa-solid fa-plus"></i>
            </div>Submit a ticket</button>

          <div data-toggle-target="togglableElement" class="d-none">
            <%# render new ticket form: %>
            <%= render 'tickets/newTicket', ticket: @ticket %>
          </div>
        </div>

        <div class="m-4" style="padding-bottom: 100px">
          <%# render tickets list %>
          <%= render "tickets/bootstrapTicketsList", tickets: @tickets %>
        </div>
      <% else %>
        <h5 class="p-5">You have not been assigned to a room yet</h5>
      <% end %>
    </div>

  </div>
</div>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/pages/ownerhistory.html.erb
<%# overalll page %>
<div class = "bg-our-back-green" style="height: 100vh">

  <% if @tickets.any? { |ticket| ticket.status == "Fixed" } %>
    <div class="list_title" style="margin-bottom: 30px; padding-top: 30px; margin-top: 0px; text-align: center;">History of tickets for <%= @sorted_house.name %></div>

    <%# search bar for history %>
    <div class="row justify-content-center">
      <div class="col-sm-8 my-3">
        <%= form_with url: ownerhistory_path, method: :get, class: "p-4 d-flex" do %>
          <%= text_field_tag :query,
                params[:query],
                class: "form-control",
                placeholder: "Search for a ticket!"
            %>

          <%= submit_tag "Search", name: "", class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>

    <div class="list-group list-group-flush"  style="border-top: 1px solid white;">

      <%# List of old tickets %>

      <%# <% @rooms.each do |room| %>

        <% @tickets.each do |ticket| %>
          <% if ticket.status == "Fixed" %>
            <%= link_to ticket_path(ticket), class: "list-group-item list-group-item-action flex-column align-items-start bg-our-back-green", style: "border-color: #FFFFFF" do %>
              <div class="d-flex w-100 justify-content-between">
                <h5 class="mb-1 mt-2"><strong><%= ticket.title %></strong></h5>
                <small class="mb-1 mt-2 status-pills status-tenant-<%= ticket.status.split(" ").join.downcase %> "><%= ticket.status %></small>
              </div>
              <p class="mb-1"><%= ticket.description.truncate(40) %></p>
            <% end %>
          <% end %>
        <% end %>
      <%# <% end %>

    <% else %>
      <p class="old-tickets" style="padding-top: 30px; text-align: center;">There are no past solved tickets for <%= "#{@sorted_house.name}" %></p>
    <% end %>

</div>
</div>

app/views/pages/tenanthistory.html.erb
<%# overalll page %>

<div class = "bg-our-back-orange" style="height: 100vh">

  <% if @tickets.any? { |ticket| ticket.status == "Fixed" } %>
    <div class="list_title" style="margin-bottom: 30px; padding-top: 30px; margin-top: 0px; text-align: center;">History of tickets for room <%= @room.number %></div>

    <% unless @room.nil? %>

      <%# search bar for history %>
      <div class="row justify-content-center">
        <div class="col-sm-8 my-3">
          <%= form_with url: tenanthistory_path, method: :get, class: "p-4 d-flex" do %>
            <%= text_field_tag :query,
                  params[:query],
                  class: "form-control",
                  placeholder: "Search for a ticket!"
              %>

            <%= submit_tag "Search", name: "", class: "btn btn-primary" %>
          <% end %>
        </div>
      </div>

      <div class="list-group list-group-flush" style="border-color: #E0702D">

        <%# List of old tickets %>
        <% @tickets.each do |ticket| %>
          <% if ticket.status == "Fixed" %>
            <%= link_to ticket_path(ticket), class: "list-group-item list-group-item-action flex-column align-items-start bg-our-back-orange",  style: "border-top: 1px solid #E0702D;" do %>
              <div class="d-flex w-100 justify-content-between">
                <h5 class="mb-1 mt-2"><strong><%= ticket.title %></strong></h5>
                <small class="mb-1 mt-2 status-pills status-tenant-<%= ticket.status.split(" ").join.downcase %> "><%= ticket.status %></small>
              </div>
              <p class="mb-1"><%= ticket.description.truncate(40) %></p>
            <% end %>
          <% end %>
      <% end %>

  <% end %>
  <% else %>
    <div class="old-tickets" style="padding-top: 30px; text-align: center;">There are no past solved tickets</div>
  <% end %>


</div>
</div>